name: yaml-marked
version: 0.0.0.0
synopsis: Support for parsing and rendering YAML documents with marks.
description: |
  TODO
category: Data
author: Pat Brisbin <pbrisbin@gmail.com>
maintainer: Pat Brisbin <pbrisbin@gmail.com>
license: MIT
github: pbrisbin/yaml-marked
stability: stable

extra-doc-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base < 5

ghc-options:
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missed-specialisations
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-safe
  - -Wno-unsafe

when:
  - condition: "impl(ghc >= 9.8)"
    ghc-options:
      - -Wno-missing-role-annotations
  - condition: "impl(ghc >= 9.2)"
    ghc-options:
      - -Wno-missing-kind-signatures
  - condition: "impl(ghc >= 8.10)"
    ghc-options:
      - -Wno-missing-safe-haskell-mode
      - -Wno-prepositive-qualified-module

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: src
  dependencies:
    - aeson
    - attoparsec
    - bytestring
    - conduit
    - containers
    - dlist
    - libyaml
    - mtl
    - resourcet
    - scientific
    - text
    - transformers
    - unliftio
    - vector
    - yaml

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N"
    dependencies:
      - aeson
      - bytestring
      - hspec
      - hspec-expectations-json
      - text
      - yaml
      - yaml-marked

  readme:
    main: README.lhs
    ghc-options: -pgmL markdown-unlit
    dependencies:
      - bytestring
      - markdown-unlit
      - text
      - yaml-marked
